config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  resources :campervans do
    resources :bookings, except: [:destroy, :edit, :update]
  end
  resources :users, only: [:show, :destroy, :index]
  resources :bookings, only: [:destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :campervan
  # validates :start_date, presence: true
  # validates :end_date, presence: true, date: { after_or_equal_to:  :start_date}
  validates_presence_of :start_date, :end_date
  validate :end_date_is_after_start_date
  validate :start_date_is_before_today


  def total_price
     self.total_price = (self.end_date - self.start_date) * self.campervan.price
  end

  private

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date")
    end
  end

  def start_date_is_before_today
    if start_date < Date.today
      errors.add(:start_date, "date cannot be before today")
    end
  end


end

app/models/campervan.rb
class Campervan < ApplicationRecord
  validates :camper_type, presence: true
  validates :camper_make, presence: true
  validates :price, presence: true
  validates :address, presence: true
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :photo, presence: true

  include PgSearch::Model
    pg_search_scope :search_by_location,
      against: [ :region ],
      using: {
        tsearch: { prefix: true } # <-- now `superman batm` will return something!
      }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :campervans, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  attr_accessor :end_date, :start_date

  def show
    @user = current_user
    @campervan = Campervan.find(params[:campervan_id])
    @booking = Booking.find(params[:id])
  end

  def new
    @campervan = Campervan.find(params[:campervan_id])
    @user = current_user
    @booking = Booking.new # Needed to instantiate the form_for
  end

  def edit
    @user = current_user
    @booking = Booking.find(params[:id])
    @campervan = @booking.campervan
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to user_path(current_user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @campervan = Campervan.find(params[:campervan_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.campervan = @campervan
    @booking.price_per_night = @campervan.price.to_i
    if @booking.save
      redirect_to campervan_booking_path(id: @booking.id, campervan_id: @campervan.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    # No need for app/views/bookings/destroy.html.erb
    redirect_to user_path(current_user), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/campervans_controller.rb
class CampervansController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @campervans = Campervan.all
    @markers = @campervans.geocoded.map do |campervan|
      {
        lat: campervan.latitude,
        lng: campervan.longitude,
        info_window: render_to_string(partial: "info_window", locals: { campervan: campervan })
      }
    end
    if params[:query].present?
    @campervans = Campervan.search_by_location(params[:query])
      if @campervans.empty?
        @campervans = Campervan.all
        flash.notice = "No campers available for this location. Showing all available campers instead."
      end
    end
  end

  def show
    @campervan = Campervan.find(params[:id])
    @campervans = Campervan.all
    @booking = Booking.new
  end

  def new
    @campervan = Campervan.new
  end

  def create
    @campervan = Campervan.new(campervan_params)
    @campervan.user = current_user
      if @campervan.save
        redirect_to campervans_path(@campervans)
      else
        render :new, status: :unprocessable_entity
      end
  end

  def edit
    @campervan = Campervan.find(params[:id])
  end

  def update
    @campervan = Campervan.find(params[:id])
    @campervan.update(campervan_params)
    redirect_to campervans_path(@campervans)
  end

  def destroy
    @campervan = Campervan.find(params[:id])
    @campervan.destroy
    redirect_to campervan_path, status: :see_other
  end

  private

  def campervan_params
    params.require(:campervan).permit(:camper_type, :camper_make, :description, :total_occupancy,
                                      :total_beds, :region, :has_bathroom,
                                      :has_shower, :has_kitchen, :has_internet,
                                      :has_tv, :price, :address, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @campervans = Campervan.all.select(params[:user_id])
    @bookings = Booking.all.select(params[:user_id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, status: :see_other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
 <div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Booking form</h2>

    <%= simple_form_for [@campervan, @booking] do |f| %>
      <%= f.input :start_date, as: :date, html5: true, input_html: {id: "start_date"} %>
      <%= f.input :end_date, as: :date, html5: true, input_html: {id: "end_date"} %>
      <%= f.button :submit, "Make Booking", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/edit.html.erb
<br>
  <div class="container" data-controller="booking-calculator" data-price=<%= @campervan.price.to_i %>>
      <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
          <h2 class="text-justify">Edit Booking Form</h2>

           <%# <h2 class="form-header">Booking form</h2> %>
          <%= simple_form_for [@booking] do |f| %>
            <%= f.input :start_date, as: :date, html5: true, input_html: {id: "start_date", data:{booking_calculator_target:"startDate"}} %>
            <%= f.input :end_date, as: :date, html5: true, input_html: {id: "end_date", data:{booking_calculator_target:"endDate", action:"change->booking-calculator#calculate"}} %>
            <%= f.button :submit, "Edit Booking", class: "btn btn-primary" %>
          <% end %>
          <br>
            <div class="d-flex justify-content-between mt-3">
              <p><strong>Price per day</strong></p>
              <p> £<%= @campervan.price  %></p>
            </div>
            <div class="d-flex justify-content-between mt-3">
              <p><strong>Start Date</strong></p>
              <p data-booking-calculator-target="startDateInput"></p>
            </div>

            <div class="d-flex justify-content-between mt-3 border-bottom">
              <p><strong>End Date</strong></p>
              <p data-booking-calculator-target="endDateInput"></p>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Total price for <em data-booking-calculator-target="numberOfDays"></em> days:</strong></p>
              <p><strong>£<em data-booking-calculator-target="totalPrice"></em></strong></p>
            </div>
    </div>
  </div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
          <div class="form-header">
            New Booking for <%= @campervan.user.first_name %>'s <%= @campervan.camper_make %>
          </div>
          <%= simple_form_for [@campervan, @booking] do |f| %>
            <%= f.input :start_date, as: :date, html5: true, input_html: {id: "start_date", data:{booking_calculator_target:"startDate"}} %>
            <%= f.input :end_date, as: :date, html5: true, input_html: {id: "end_date", data:{booking_calculator_target:"endDate", action:"change->booking-calculator#calculate"}} %>
            <%= f.button :submit, "Edit Booking", class: "btn btn-primary" %>
          <% end %>
          <br>
            <div class="d-flex justify-content-between mt-3">
              <p><strong>Price per day</strong></p>
              <p> £<%= @campervan.price  %></p>
            </div>
            <div class="d-flex justify-content-between mt-3">
              <p><strong>Start Date</strong></p>
              <p data-booking-calculator-target="startDateInput"></p>
            </div>

            <div class="d-flex justify-content-between mt-3 border-bottom">
              <p><strong>End Date</strong></p>
              <p data-booking-calculator-target="endDateInput"></p>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Total price for <em data-booking-calculator-target="numberOfDays"></em> days:</strong></p>
              <p><strong>£<em data-booking-calculator-target="totalPrice"></em></strong></p>
            </div>
       </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
  <br>
    <h1>Booking request sent!</h1>
    <p>Thank you for your request to book <%= @campervan.user.first_name %>'s <%= @campervan.camper_type %>!</p>
    <p>Dates from <%= @booking.start_date %> until <%= @booking.end_date %>. <%= @campervan.user.first_name  %> will respond within 24 hours!</p>
    <%= link_to "View My Account", user_path(current_user), class: "btn btn-ghost" %>
    <br>
    <br>
    <div class="camper-img-1">
      <%= cl_image_tag @campervan.photo.key %>
    </div>

  </div>
</div>

app/views/campervans/_form.html.erb
<div class="form-image">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="container-form" >
          <div class="form-header">
            Add a camper
          </div>
          <%= simple_form_for(@campervan) do |f| %>
            <div class="row">
              <div class="col">
                <%= f.input :camper_type %>
              </div>
              <div class="col">
                <%= f.input :camper_make %>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <%= f.input :total_occupancy %>
              </div>
              <div class="col">
                <%= f.input :total_beds %>
              </div>
            </div>

            <div class="col">
              <%= f.input :description %>
            </div>

            <div class="row">
              <div class="col">
                <%= f.input :has_bathroom %>
                <%= f.input :has_shower %>
                <%= f.input :has_kitchen %>
              </div>
              <div class="col">
                <%= f.input :has_internet %>
                <%= f.input :has_tv %>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <%= f.input :region %>
              </div>
              <div class="col">
                <%= f.input :address,
                input_html: {data: {address_autocomplete_target: "address"}, class: "hidden"},
                wrapper_html: {data: {controller: "address-autocomplete",
                address_autocomplete_api_key_value:
                ENV["MAPBOX_API_KEY"]}} %>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <%= f.input :price %>
              </div>
              <div class="col">
                <%= f.input :photo, as: :file %>
              </div>
            </div>
            <%= f.submit class: "btn-form" %>
          <% end %>
        </div>
      </div>
      <div class="col">
      </div>
    </div>
  </div>
</div>

app/views/campervans/_info_window.html.erb
<div class="info-window">

  <div class="row">
      <%= cl_image_tag campervan.photo.key, crop: :fill%>
  </div>

  <div class="row">
    <h4> <%= link_to campervan.camper_type, campervan_path(campervan) %></h4>
  </div>

 <div class="border-bottom"></div>


  <div class="row d-flex justify-content-between">
      <div class="col">
        <h5 style="margin:0" ><i class="fa-solid fa-person"></i> <%= campervan.total_occupancy %> </h5>
      </div>

      <div class="col">
       <h5> <span class="badge bg-secondary"> £<%= campervan.price.to_i %> /night </span> </h5>
      </div>

  </div>

</div>

app/views/campervans/edit.html.erb
<%= render "form", campervan: @campervan %>

app/views/campervans/index.html.erb
<%# <div class="camper-banner mb-4 d-flex align-items-center justify-content-center">
  <div class="text-left text-white">
    <div class="container">
      <div class="hero-text">
        <h1>Campers</h1>
      </div>
    </div>
  </div>
</div> %>

<div class="container-index">
  <div class="cards-demo">
    <% @campervans.each do |campervan|%>
      <div class="card-demo">
        <%= link_to campervan_path(campervan) do %>
          <%# image %>
              <%= cl_image_tag campervan.photo.key, height: 300, crop: :fill, class:"carousel-image" %>
          <div class="card-info-container">

            <div class="owner-div" >
              <p style="margin:0">Owner: <%= campervan.user.first_name %> </p>
            </div>


            <div class="info-div">
              <p style="margin:0" ><i class="fa-solid fa-person"></i> <%= campervan.total_occupancy %> </p>
              <p style="margin:0"><i class="fa-solid fa-bed"></i> <%= campervan.total_beds %> </p>
              <p style="margin:0"><i class="fa-solid fa-location-dot"></i><%= campervan.region %></p>
            </div>


            <div class="booking-btn">

              <p style="margin:0"> <strong>£<%= campervan.price.to_i %></strong> / night </p>
              <%= link_to "Book Now!", campervan_path(campervan), class: "btn btn-ghost" %>
            </div>

          </div>
        <%end%>
      </div>
    <%end%>
  </div>
  <div class="map-container" style="width: 30vw; height: 90vh;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/campervans/show.html.erb
<div class="camper-p-grid">
  <div class="camper-column-left">
    <div class="camper-header">
       <h3 ><%=@campervan.camper_type%></h3>
      <p><i class="fa-solid fa-location-dot"></i><%= @campervan.region %></p>
    </div>


        <div class="camper-p-image">
            <% if @campervan.photo.key %>
              <%= cl_image_tag @campervan.photo.key, class: "camper-p-image" %>
            <%end%>
        </div>

        <div class="profile-box profile-information">
            <div class="title-camper"><%= @campervan.description %> </div>

            <div class="capacity-container">
              <div class="capacity-contents">
                <div class="capacity-header">Capacity:</div>
                <% (@campervan.total_occupancy).times do %>
                <i class="fa-solid fa-person"></i>
                <%end%>

              </div>

              <div class="capacity-contents">
                <div class="capacity-header">Beds:</div>
                <% (@campervan.total_beds).times do %>
                <i class="fa-solid fa-bed"></i>
                <%end%>
              </div>
            </div>

            <div class="capacity-header-amenity">What the camper offers:</div>
            <div class="capacity-container-amenities">
              <div class="amenity">
                  <% if @campervan.has_bathroom? %>
                  <i class="fa-solid fa-toilet"></i> Toilet
                  <%else%>
                    <i class="fa-regular fa-circle-xmark"></i> Toilet
                  <% end %>
              </div>

              <div class="amenity">
                  <% if @campervan.has_shower? %>
                    <i class="fa-solid fa-shower"></i> Shower
                  <%else%>
                    <i class="fa-regular fa-circle-xmark"></i> Shower
                  <% end %>
              </div>

              <div class="amenity">
                  <% if @campervan.has_kitchen? %>
                  <i class="fa-solid fa-kitchen-set"></i> Kitchen
                  <%else%>
                    <i class="fa-regular fa-circle-xmark"></i> Kitchen
                  <% end %>
              </div>


              <div class="amenity">
                  <% if @campervan.has_internet? %>
                  <i class="fa-solid fa-wifi"></i> Wifi
                  <%else%>
                    <i class="fa-regular fa-circle-xmark"></i> Wifi
                  <% end %>
              </div>

              <div class="amenity">
                <% if @campervan.has_tv? %>
                <i class="fa-solid fa-tv"></i> TV
                <%else%>
                    <i class="fa-regular fa-circle-xmark"></i> TV
                <% end %>
              </div>
            </div>

            <%# descriptioned needed %>


            <div class="capacity-container-amenities">
              <div class="amenity">
                <%= link_to "Edit", edit_campervan_path(@campervan), class: "btn-ghost"%>
              </div>

            </div>

        </div>



  </div>

  <div class="camper-column-right">
    <div class="cp-information">
        <div class="container-form-camper">
            <div class="container" data-controller="booking-calculator" data-price=<%= @campervan.price.to_i %>>
                <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
                    <h2 class="form-header">Booking Request Form</h2>

            <%# <h2 class="form-header">Booking form</h2> %>
            <%= simple_form_for [@campervan, @booking] do |f| %>
              <%= f.input :start_date, as: :date, html5: true, input_html: {id: "start_date", data:{booking_calculator_target:"startDate"}} %>
              <%= f.input :end_date, as: :date, html5: true, input_html: {id: "end_date", data:{booking_calculator_target:"endDate", action:"change->booking-calculator#calculate"}} %>
              <%= f.button :submit, "Make Booking Request", class: "btn btn-form-camper" %>
            <% end %>
            <br>
              <div class="d-flex justify-content-between mt-2">
                <p><strong>Price per day</strong></p>
                <p> £<%= @campervan.price  %></p>
              </div>
              <div class="d-flex justify-content-between mt-2">
                <p><strong>Start Date</strong></p>
                <p data-booking-calculator-target="startDateInput"></p>
              </div>

              <div class="d-flex justify-content-between mt-2 border-bottom">
                <p><strong>End Date</strong></p>
                <p data-booking-calculator-target="endDateInput"></p>
              </div>

              <div class="d-flex justify-content-between mt-2">
                <p><strong>Total price for <em data-booking-calculator-target="numberOfDays"></em> days:</strong></p>
                <p><strong>£<em data-booking-calculator-target="totalPrice"></em></strong></p>
              </div>
          </div>
    </div>

  </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeCampeur</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
  <div class="wrapper">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <p style="margin:0; display:none" class="notice"><%= notice %></p>
    <p style="margin:0" class="alert"><%= alert %></p>
    <%= yield %>
    <div class="push"></div>
  </div>
  <div class="footer">
    <%= render "shared/footer" %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-left text-white">
    <div class="container">
      <div class="hero-text">
      <% if current_user %>
        <h1 class="typed-js">Hey, <%= @user.first_name %>. Book your next camper adventure now!</h1>
      <% else %>
        <h1 class="typed-js">Don't just imagine; book your next camper adventure now!</h1>
      <% end %>
      </div>
    </div>
    <div class="container" >
      <%= form_tag campervans_path, method: :get, class: "d-flex search-form" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",

          placeholder: "Search for campers near you." %>
          <%# , input_html: {data: {address_autocomplete_target: "address"}},
                wrapper_html: {data: {controller: "address-autocomplete",
                address_autocomplete_api_key_value:
                ENV["MAPBOX_API_KEY"]}}  %>
        <%= submit_tag "Search", class: "btn btn-flat" %>
      <% end %>
      <br>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> </button>
    <%= notice %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/harrybremner/le_campeur"><i class="fab fa-github"></i></a>
    <%= link_to "About", root_path, class: "nav-link" %>
    <%= link_to "FAQs", root_path, class: "nav-link" %>
    <%= link_to "Contact", root_path, class: "nav-link" %>
  </div>
  <div class="footer-copyright">
    Copyright <i class="fas fa-copyright"></i> Contio
  </div>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <li class="nav-item active navbar-nav me-auto">
          <%= link_to root_path, class: "nav-link" do%>
          <i class="fa-solid fa-van-shuttle fa-bounce" style=" --fa-bounce-start-scale-x: 1; --fa-bounce-start-scale-y: 1; --fa-bounce-jump-scale-x: 1; --fa-bounce-jump-scale-y: 1; --fa-bounce-land-scale-x: 1; --fa-bounce-land-scale-y: 1;" ></i> Le Campeur
          <%end%>
      </li>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active" style="padding-top:8px; padding-right:12px">
            <%= link_to "Browse all campervans", campervans_path, class: "btn-nav" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<br>
<br>
<div class="container">
  <div class="user-profile">
    <div class="card-user row justify-content-evenly">
      <div class="card-category col-4">
        <% @users.each do |user|%>
        <% if user.photo.key %>
            <%= cl_image_tag current_user.photo.key, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <%= link_to user.first_name, user_path(user) %>
        <%= user.first_name %> <%= user.last_name %>
        <%= link_to "Delete", user_path(user), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-grid">
  <div class="profile-column-left">
    <h3 class="profile-header"><%=@user.first_name%></h3>
    <div class="profile-image">
      <% if @user.photo.key %>
        <%= cl_image_tag current_user.photo.key, class: "card-img-top", style: "border-radius: 5px; max-height: 100%; object-fit: cover", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
    </div>
    <div class="profile-box profile-information">
            <p>Email: <%= @user.email %> </p>
            <p>Account created: <%= @user.created_at.mday %>/<%= @user.created_at.month %>/<%= @user.created_at.year %></p>
            <p>Number of Bookings: <%= @bookings.all.count %>
            <p>Number of Campervans: <%= @campervans.all.count %>
          <div class="profile-button">
            <%= link_to "Edit Profile", edit_user_registration_path(current_user), class: "btn btn-ghost"%>
            <%= link_to "Create new campervan", new_campervan_path(), class: "btn btn-ghost"%>
          </div>
    </div>
  </div>


  <div class="profile-column-right">


  <% if @user.bookings.present? %>
      <div class="booking-box booking-section">

          <div class="c">
          <h3>My Bookings:</h3>
            <% @bookings.each do |booking|%>
            <div class="spacing-camper-box">
              <div class="camper-box">
                <% if booking.campervan.photo.key %>
                    <%= cl_image_tag booking.campervan.photo.key, class: "campervan-image" %>
                <% end %>
                <div class="camper-information">
                  <h3 class="booking-header"><%= booking.campervan.camper_type %></h3>
                  <div class="profile-information">
                  <p>Start: <%= booking.start_date  %></p>
                  <p>End: <%= booking.end_date %></p>
                  <p>Total price: £<%= booking.total_price  %></p>
                  </div>
                  <%= link_to "Edit Booking", edit_booking_path(booking), class: "btn btn-ghost"%>

                  <%= link_to "Cancel Booking", booking_path(booking), class: "btn btn-ghost", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                </div>
              </div>
            </div>
              <% end %>

          </div>
      </div>
  <% end %>

  <div class="booking-box camper-section">
    <div class="c">
    <h3 >My Campervans:</h3>
     <% @campervans.each do |campervan|%>
      <div class="spacing-camper-box">
        <div class="camper-box">
          <% if campervan.photo.key %>
              <%= cl_image_tag campervan.photo.key, class: "campervan-image" %>
          <% end %>

          <div class="camper-information">
          <h3 class="booking-header"><%= campervan.camper_type %></h3>
          <div class="profile-information">
                        <p class="card-text"><%= campervan.camper_make  %></p>
                        <p><i class="fa-solid fa-location-dot"></i><%= campervan.region %></p>
          </div>
                        <%= link_to "View", campervan_path(campervan), class: "btn btn-ghost" %>
                        <%= link_to "Delete", campervan_path(campervan), class: "btn btn-ghost", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

          </div>
          </div>
      </div>
      <% end %>
    </div>
  </div>




  </div>
</div>

    <!-- user info -->